-- /home/user/.config/koreader/settings.reader.lua
return {
    ["auto_save_settings_interval_minutes"] = 15,
    ["autodim_duration_seconds"] = 5,
    ["autodim_fraction"] = 20,
    ["autodim_starttime_minutes"] = -1,
    ["autoturn_distance"] = 1,
    ["autoturn_timeout_seconds"] = 0,
    ["autowarmth_fl_off_during_day"] = false,
    ["autowarmth_fl_off_during_day_offset_s"] = 0,
    ["autowarmth_timezone"] = 0,
    ["back_in_filemanager"] = "default",
    ["back_in_reader"] = "previous_location",
    ["back_to_exit"] = "prompt",
    ["book_map_ten_pages_markers"] = 0,
    ["bookmarks_items_font_size"] = 19,
    ["bookmarks_items_per_page"] = 14,
    ["bookmarks_items_text_type"] = "note",
    ["closed_rotation_mode"] = 0,
    ["collate"] = "strcoll",
    ["color_rendering"] = false,
    ["coverbrowser_initial_default_setup_done"] = true,
    ["cre_font_family_fonts"] = {},
    ["cre_fonts_recently_selected"] = {
        [1] = "Droid Sans Mono",
        [2] = "FreeSans",
        [3] = "FreeSerif",
        [4] = "Noto Naskh Arabic",
        [5] = "Noto Sans",
        [6] = "Noto Sans Arabic UI",
        [7] = "Noto Sans Bengali UI",
        [8] = "Noto Sans CJK SC",
        [9] = "Noto Sans Devanagari UI",
        [10] = "Noto Serif",
    },
    ["cre_header_author"] = 1,
    ["cre_header_auto_refresh"] = 1,
    ["cre_header_battery"] = 1,
    ["cre_header_battery_percent"] = 0,
    ["cre_header_chapter_marks"] = 1,
    ["cre_header_clock"] = 1,
    ["cre_header_page_count"] = 1,
    ["cre_header_page_number"] = 1,
    ["cre_header_reading_percent"] = 0,
    ["cre_header_status_font_size"] = 20,
    ["cre_header_title"] = 1,
    ["default_highlight_action"] = "ask",
    ["dev_no_c_blitter"] = false,
    ["device_id"] = "15108310129A41AD8DA38CE7D5AF23CA",
    ["device_status_battery_interval_minutes"] = 10,
    ["device_status_battery_threshold"] = 20,
    ["device_status_battery_threshold_high"] = 100,
    ["device_status_memory_interval_minutes"] = 5,
    ["device_status_memory_threshold"] = 100,
    ["dict_presets"] = {},
    ["dicts_disabled"] = {},
    ["dicts_order"] = {},
    ["dimension_units"] = "mm",
    ["document_metadata_folder"] = "doc",
    ["duration_format"] = "classic",
    ["exporter"] = {
        ["flomo"] = {
            ["enabled"] = false,
        },
        ["html"] = {
            ["enabled"] = false,
        },
        ["joplin"] = {
            ["enabled"] = false,
        },
        ["json"] = {
            ["enabled"] = false,
        },
        ["markdown"] = {
            ["formatting_options"] = {
                ["invert"] = "bold",
                ["lighten"] = "italic",
                ["strikeout"] = "strikethrough",
                ["underscore"] = "underline_markdownit",
            },
            ["highlight_formatting"] = true,
        },
        ["memos"] = {
            ["enabled"] = false,
        },
        ["my_clippings"] = {
            ["enabled"] = false,
        },
        ["readwise"] = {
            ["enabled"] = false,
        },
        ["text"] = {
            ["enabled"] = false,
        },
        ["xmnote"] = {
            ["enabled"] = false,
        },
    },
    ["extra_plugin_paths"] = {
        [1] = "/home/user/.config/koreader/plugins/",
    },
    ["filemanagermenu_tab_index"] = 5,
    ["folder_shortcuts"] = {},
    ["footer"] = {
        ["align"] = "center",
        ["all_at_once"] = false,
        ["auto_refresh_time"] = false,
        ["battery"] = true,
        ["battery_hide_threshold"] = 100,
        ["book_author"] = false,
        ["book_author_max_width_pct"] = 30,
        ["book_chapter"] = false,
        ["book_chapter_max_width_pct"] = 30,
        ["book_time_to_read"] = true,
        ["book_title"] = false,
        ["book_title_max_width_pct"] = 30,
        ["bookmark_count"] = false,
        ["bottom_horizontal_separator"] = false,
        ["chapter_progress"] = false,
        ["chapter_progress_bar"] = false,
        ["chapter_time_to_read"] = true,
        ["container_bottom_padding"] = 1,
        ["container_height"] = 14,
        ["disable_progress_bar"] = false,
        ["disabled"] = false,
        ["frontlight"] = false,
        ["hide_empty_generators"] = false,
        ["initial_marker"] = false,
        ["item_prefix"] = "icons",
        ["items_separator"] = "bar",
        ["lock_tap"] = false,
        ["mem_usage"] = false,
        ["page_progress"] = true,
        ["pages_left"] = true,
        ["pages_left_book"] = false,
        ["pages_left_includes_current_page"] = false,
        ["percentage"] = true,
        ["progress_bar_min_width_pct"] = 20,
        ["progress_bar_position"] = "alongside",
        ["progress_margin"] = false,
        ["progress_margin_width"] = 10,
        ["progress_pct_format"] = "0",
        ["progress_style_thick_height"] = 7,
        ["progress_style_thin"] = false,
        ["progress_style_thin_height"] = 3,
        ["reclaim_height"] = false,
        ["skim_widget_on_hold"] = false,
        ["text_font_bold"] = false,
        ["text_font_size"] = 14,
        ["time"] = true,
        ["toc_markers"] = true,
        ["toc_markers_width"] = 2,
        ["wifi_status"] = false,
    },
    ["footer_presets"] = {},
    ["ges_tap_interval_on_keyboard_ms"] = 0,
    ["highlight_dialog_position"] = "center",
    ["highlight_lighten_factor"] = 0.2,
    ["highlight_long_hold_threshold_s"] = 3,
    ["history_filter"] = "all",
    ["home_dir"] = "/home/user/Documents/calibre",
    ["httpinspector_port"] = "8080",
    ["inertial_scroll"] = true,
    ["keyboard_key_font_size"] = 22,
    ["keyboard_layouts"] = {},
    ["kosync"] = {
        ["auto_sync"] = true,
        ["checksum_method"] = 1,
        ["sync_backward"] = 3,
        ["sync_forward"] = 1,
        ["userkey"] = "e123864f01d24310b070d2d2be74fdd2",
        ["username"] = "trumpetrespas",
    },
    ["language"] = "en_GB",
    ["last_migration_date"] = 20250929,
    ["lastdir"] = "/etc/sway_hrdl/sway",
    ["lastfile"] = "/home/user/Books/Terry Pratchett/Terry Pratchett - [Discworld 20] - Hogfather (1996) (v4.9) (epub).epub",
    ["night_mode"] = false,
    ["page_browser_nb_cols"] = 4,
    ["page_browser_nb_rows"] = 1,
    ["page_browser_thumbnails_pagenums"] = 2,
    ["page_turns_tap_zones"] = "default",
    ["panel_zoom_enabled"] = {
        ["cbt"] = true,
        ["cbz"] = true,
    },
    ["panel_zoom_fallback_to_text_selection"] = {
        ["pdf"] = true,
    },
    ["profiles_autoexec"] = {},
    ["provider"] = {},
    ["quickstart_shown_version"] = 202407000000,
    ["reader_footer_custom_text"] = "KOReader",
    ["reader_footer_custom_text_repetitions"] = "1",
    ["reader_footer_mode"] = 4,
    ["readtimer"] = {},
    ["screensaver_delay"] = "disable",
    ["screensaver_hide_fallback_msg"] = false,
    ["screensaver_img_background"] = "black",
    ["screensaver_message_alpha"] = 100,
    ["screensaver_message_container"] = "box",
    ["screensaver_message_vertical_position"] = 50,
    ["screensaver_msg_background"] = "none",
    ["screensaver_rotate_auto_for_best_fit"] = false,
    ["screensaver_show_message"] = true,
    ["screensaver_stretch_images"] = false,
    ["screensaver_type"] = "disable",
    ["scroll_method"] = "classic",
    ["sdl_window"] = {
        ["height"] = 1347,
        ["left"] = 941,
        ["top"] = 50,
        ["width"] = 924,
    },
    ["show_filter"] = {},
    ["start_with"] = "last",
    ["statistics"] = {
        ["calendar_browse_future_months"] = false,
        ["calendar_nb_book_spans"] = 3,
        ["calendar_show_histogram"] = true,
        ["calendar_start_day_of_week"] = 2,
        ["convert_to_db"] = true,
        ["freeze_finished_books"] = false,
        ["is_enabled"] = true,
        ["max_sec"] = 120,
        ["min_sec"] = 5,
    },
    ["style_tweaks"] = {
        ["footnote-inpage_epub"] = true,
        ["footnote-inpage_fb2"] = true,
        ["inpage_footnote_font-size_smaller"] = true,
    },
    ["style_tweaks_in_dispatcher"] = {},
    ["terminal_buffer_size"] = 16,
    ["terminal_shell"] = "/usr/bin/bash",
    ["text_lang_fallback"] = "en-US",
    ["toc_items_per_page"] = 14,
    ["vocabulary_builder"] = {
        ["enabled"] = false,
        ["with_context"] = true,
    },
}
