return {
  "folke/snacks.nvim",
  priority = 1000,
  lazy = false,
  opts = {
    image = { enabled = true },
    -- disable everything else
    animate      = { enabled = false },
    bigfile      = { enabled = false },
    bufdelete    = { enabled = false },
    dashboard    = { enabled = false },
    debug        = { enabled = false },
    dim          = { enabled = false },
    explorer     = { enabled = false },
    git          = { enabled = false },
    gitbrowse    = { enabled = false },
    indent       = { enabled = false },
    input        = { enabled = false },
    lazygit      = { enabled = false },
    layout       = { enabled = false },
    notifier     = { enabled = false },
    picker       = { enabled = false },
    profiler     = { enabled = false },
    quickfile    = { enabled = false },
    rename       = { enabled = false },
    scope        = { enabled = false },
    scratch      = { enabled = false },
    scroll       = { enabled = false },
    statuscolumn = { enabled = false },
    terminal     = { enabled = false },
    toggle       = { enabled = false },
    win          = { enabled = false },
    words        = { enabled = false },
    zen          = { enabled = false },
  },
}
